# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-04 09:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='update_date',
            new_name='updated_date',
        ),
    ]
