# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-04 09:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180904_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='publish_date',
            new_name='publish_at',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='updated_date',
            new_name='updated_at',
        ),
    ]
