# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-04 09:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180904_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='publish_at',
            new_name='published_at',
        ),
    ]
