# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-06 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180904_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='plop', max_length=100),
            preserve_default=False,
        ),
    ]
